### PR TITLE
Added nodejs-yarn 

### PR DESCRIPTION
**Pull request by kulikovav**
* Added new spec file for yarn (https://yarnpkg.com/en/)

### CODE REVIEW

**Comment by kulikovav** [comment]
@andyone Hi! Could you please have a glance on this PR? I can't figure out why the build failed.

**Comment by andyone** [comment]
Hi! The latest version of `perfecto` found a lot of problems with specs in the development branch. It's ok. This spec has only one problem (_line 69_):

```[69] (PF2) Line is longer than 80 symbols```

More info: https://kaos.sh/perfecto/w/PF2

**Comment by andyone** [comment]
@kulikovav I have fixed all the problems reported by perfecto in the development branch, and after syncing with the origin, all of them should be gone.

**Comment by andyone** [comment]
Looks good, merged. Thanks!

**Comment by andyone** [comment]
The package was built and added to `kaos-testing` repository.

**Comment by kulikovav** [comment]
Thank you!

**Pull request merged**
