### PR TITLE
libnut: spec refactoring

### PR DESCRIPTION
**Pull request by gongled**
I prepared `libnut` and `libnub-devel` package for NUT multimedia container library. It's optional requirement for FFmpeg. Unfortunately, I don't know where is source code of this project. I've found [this one](https://github.com/TimothyGu/libnut) and built package using this command:

```
rpmbuilder libnut.spec -V --git https://github.com/TimothyGu/libnut.git -rr f3476bb3ccf5acc1b0be76fc881f1e804c475391
```

### CODE REVIEW

**Comment by andyone** [comment]
@gongled `rpmbuilder` support some definitions inside a spec. Just add this lines on top of your spec file:

```
# rpmbuilder:github   TimothyGu/libnut
# rpmbuilder:revision f3476bb3ccf5acc1b0be76fc881f1e804c475391
```

In this case, if rpmbuilder will be used for build, rpmbuilder download sources from TimothyGu repo on github and pack it with name defined in `Source0`.

**Comment by andyone** [comment]
You can simplify command and use this one:
`rpmbuilder libnut.spec -V -gh TimothyGu/libnut -rr f3476bb3ccf5acc1b0be76fc881f1e804c475391`

**Comment by gongled** [comment]
Thanks! I did it. (https://github.com/essentialkaos/kaos-repo/pull/47/commits/a79e3d27862cd8a0f486edfce33857a061554b89)

**Comment by andyone** [comment]
Thanks!

**Pull request merged**
