### PR TITLE
Release (2016/08/02)

### PR DESCRIPTION
**Pull request by andyone**
- [x] `zabbix` updated to 3.0.3-1 (_removed unnecessary patch_)
- [x] `ansible-lint` updated to 3.0.0
- [x] `postgresql92` added installing `pg_config` link using update-alternatives
- [x] `postgresql93` added installing `pg_config` link using update-alternatives
- [x] `postgresql94` added installing `pg_config` link using update-alternatives
- [x] `postgresql95` added installing `pg_config` link using update-alternatives
- [x] `elixir` updated to 1.3.1
- [x] `vsftpd` updated to 3.0.3-1 (_added PAM configuration_)
- [x] `nodejs` updated to 4.4.7
- [x] `ejabberd` updated to 16.06
- [x] `haproxy` updated to 1.6.7
- [x] `golang` updated to 1.6.3
- [x] `vips` updated to 8.3.1
- [x] `cronie` updated to 1.5.1

### CODE REVIEW

**Comment by gongled** [comment]
@andyone probably, you should include `ejabberd` package in your list.

**Comment by andyone** [comment]
@gongled Yes, you right. Thanks.

**Comment by simukti** [comment]
Hello @andyone , is this the right place to suggest golang v1.6.3 ?

**Comment by andyone** [comment]
@simukti No. If you want to suggest update for golang package, you should create new issue in this repo and I prepare spec for new version.

**Pull request merged**
