### PR TITLE
Zabbix updated to 3.4.1

### PR DESCRIPTION
**Pull request by kulikovav**

### CODE REVIEW

**Comment by andyone** [comment]
Hi, thanks for PR.

- Why do you move some options from `build_flags` to `%configure`?
- Please add full changelog for this version

**Comment by kulikovav** [comment]
SQLite database backend support was removed from zabbix server. The configure phase fails if both --with-server and --with-sqlite3 options are specified.

**Comment by andyone** [comment]
Ok, thanks for explanation.

**Comment by kulikovav** [comment]
> Please add full changelog for this version

done

**Comment by andyone** [comment]
Looks good for me now. Merged.

**Pull request merged**
