### PR TITLE
Update Kafka to 1.0.1

### PR DESCRIPTION
**Pull request by gongled**
[Kafka 1.0.0](https://dist.apache.org/repos/dist/release/kafka/1.0.0/RELEASE_NOTES.html) was released in November, 1, so I decided to brush up the RPM spec:

- Added systemd unit for CentOS/RHEL 7 support.
- Improved Kafka dependencies list: remove `jdk8` package, use `java-devel` instead. It might be useful for those people, who want to use OpenJDK as a main JDK during on building process.
- Changed `offsets.topic.replication.factor` from 2 to 1 because we should try to minimize the configuration steps by default. Offsets replication factor 2 means that you have to have at least 2 nodes of Kafka's in your cluster to keep up an offsets of partitions.
- Changed `zookeeper.connect` from `localhost:60182` to `localhost:2181` to the default Zookeeper port. We still need to have a Zookeeper installed before starting use Kafka, but the default port is easy to recognize.

### CODE REVIEW

**Comment by andyone** [comment]
Thanks for your contribution!

**Comment by gongled** [comment]
I found an issue of memory leak for Kafka 1.0.0 (https://issues.apache.org/jira/browse/KAFKA-6185). Maybe we should wait release 1.1.0 or apply patch, that have been already merged to trunk branch (https://github.com/apache/kafka/pull/4193).

**Comment by andyone** [comment]
I think it better to wait for [1.0.1 release](https://issues.apache.org/jira/projects/KAFKA/versions/12341619) which also contains fixes for other important bugs.

**Comment by andyone** [comment]
@gongled Could you please merge your branch with the latest version of `develop` branch? It must fix a problem with TravisCI checks.

**Comment by gongled** [comment]
Sometimes I need to install libraries without configuring the whole broker with Zookeeper and so forth. So, while we are waiting for 1.0.1 release, I decided to separate `kafka` packages to `kafka-server` (systemd unit, configuration file, log directories, etc.) and `kafka` (application with client-side tools). JFYI.

**Comment by gongled** [comment]
Kafka 1.0.1 has been finally released with the fix that we are waiting for so long. However, I want to inform you that I have not tested upgrade yet. I suggest to check it and then include the following package to the next release.

**Comment by gongled** [comment]
@andyone, I've checked installation and upgrade procedure from 0.11.0 to 1.0.1. At first glance, it works properly. Could you build and publish new package to `kaos-testing`?

**Comment by andyone** [comment]
@gongled Because of a massive number of commits in this PR, I decided to add all these changes as single commit (7afacc73968c7c9c3b3e1bb3cc5bc249440b0917) to develop branch.

**Comment by andyone** [comment]
I have added `kafka-1.0.1` to `kaos-testing` repository. I'll release this package as part of #180

If you find some problems with the spec or configs, please create new PR from develop branch. It will be much easier to review changes to me.

**Pull request closed without merging**
