### PR TITLE
Add Apache Maven 3.6.1

### PR DESCRIPTION
**Pull request by gongled**
Hi, @andyone.

I ask you to build, verify and publish RPM spec for Apache Maven. Unfortunately, CentOS 7 provides Maven 3.0.5 whose version is too old to build lots of Java software (such as Kafka, Kafka REST Proxy and so forth). I made an attempt to adopt package to `maven-3.5.4` from Fedora 30 to Fedora Guidelines. And I hope it looks well.

### CODE REVIEW

**Comment by andyone** [comment]
Hi! This package needs bibop tests because I think we can't add so important build tool to our repository without any tests.

**Review by andyone — CHANGES_REQUESTED** [review]
[bibop](https://github.com/essentialkaos/bibop) tests are mandatory for all new specs.

**Review by gongled — COMMENTED** [review]
OK. I'm going to finish writing bibop test today.

**Review by gongled — COMMENTED** [review]
Ready for review.

**Comment by andyone** [comment]
Looks like the latest version of _perfecto_ is not happy with bash loops in this spec 😉

**Comment by andyone** [comment]
> Ready for review.

In the Reviewers section on the right side of PR page, as an author you should have a small circle with arrows, clicking on it mark that PR as ready for review. Because I can accidentally skip such kind of the message.

**Review by gongled — COMMENTED** [review]
Satisfied perfecto checks.

**Comment by gongled** [comment]
> Looks like the latest version of _perfecto_ is not happy with bash loops in this spec 😉

Fixed (cffbe68af2913726a52e65f9885780dc5cc9e641)

**Comment by gongled** [comment]
> [bibop](https://github.com/essentialkaos/bibop) tests are mandatory for all new specs.

Fixed (65bbff5c898a5ac07c9d2e3bed43b0a7409b4bc7)

**Review by andyone — APPROVED** [review]

**Comment by andyone** [comment]
@gongled Hi! I have created a spec for maven with the binary release. It's based on your PR but also contains a new checksum validation feature from the latest version of `rpmbuilder` and uses JDK from our repo (_at this moment we provide JDK 8, 9, 10, 11, 12 and 13 for both supported OS's_). 

Thanks a lot for your contribution.

**Pull request closed without merging**
