### PR TITLE
Added libgit2 and python-pygit2

### PR DESCRIPTION
**Pull request by kulikovav**
* Added new spec files for libgit2 and python-pygit2 packages
* Fixed issue with importing backports.ssl_match_hostname module under Python 2.x

### CODE REVIEW

**Comment by andyone** [comment]
Looks good, merged. Thanks!

**Comment by andyone** [comment]
@kulikovav FYI there are no packages like `python34-backports` and `python36-backports`, so I have reverted changes from this PR for `python3-backports-ssl_match_hostname.spec`.

**Comment by kulikovav** [comment]
> @kulikovav FYI there are no packages like `python34-backports` and `python36-backports`, so I have reverted changes from this PR for `python3-backports-ssl_match_hostname.spec`.

Thanks for noticing that. Is there any reason why we need to have python3-backports-ssl_match_hostname package?

**Comment by andyone** [comment]
I think yes. In [setup.py](https://bitbucket.org/brandon/backports.ssl_match_hostname/src/default/setup.py) file defined that this module supports Python up to 3.7, and they [test it](https://bitbucket.org/brandon/backports.ssl_match_hostname/src/312648aec6f01702e8704a99b54445ffc2458033/tox.ini#lines-2) for 3.x.

And if I understand it right, the latest version of the module contains backported functions from 3.7 for all previous versions.

**Pull request merged**
