### PR TITLE
Improve Zookeeper RPM spec

### PR DESCRIPTION
**Pull request by gongled**
I propose you to add Apache Zookeeper to EK repository. I already built this package long time ago, but I packed only binaries. I improved Zookeeper RPM spec. Now it can be built from the source code. Also package contains `zkcli` utility which is useful to connect to Zookeeper directly.

### CODE REVIEW

**Comment by andyone** [comment]
Nice work!

**Comment by andyone** [comment]
@gongled Please notify me when I can merge it.

**Comment by gongled** [comment]
@andyone now it looks good for me. Lets merge it.

**Comment by andyone** [comment]
Merged, thanks.

**Pull request merged**
